### ISSUE TITLE
Queues are not processed, the cleanup request queue is hanging

### ISSUE THREAD

**Issue by floriankammermann** [swisspush/vertx-redisques#12]
We had now twice the situation, where the cleanup queue was hanging. This led to the situation that other queues were hanging too, because the cleanup request couldn't reach redisques.

The sequence:

1. The scheduler triggers the cleanup request
2. The cleanup request itself is sent to redisques over the Eventbus
3. The cleanup request gets queued
4. The cleanup request will be handled by the QueueProcessor
5. The cleanup request is sent to the router
6. The cleanup request will be handled by a hardcoded rule, which triggers a check on RedisQues over the EventBus
7. the cleanup request triggers the check API call on redisques https://github.com/swisspush/vertx-redisques#check

The problem is, that if the this sequence fails at some point, then its possible that queues are not processed and the cleanup itself could be blocked too, which could lead to a deadlock situation.

**Comment by floriankammermann** [comment]
Could possibly be solved by #10

**Comment by lbovet** [comment]
"Le serpent qui se mord la queue"
Indeed, there is something stupid in queuing messages dedicated to unlock queues...
We should maybe have an option in the scheduler to _not_ queue the scheduled request. But this is a gateleen issue.

**Comment by floriankammermann** [comment]
Resolved with https://github.com/swisspush/vertx-redisques/pull/14
