### ISSUE TITLE
Stabilize RedisQues by improving error handling (review of v2.5.1)

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/vertx-redisques#59]
We regularly run into trouble with unexpected behaviour like _never answered
requests_ etc.

Therefore we performed a code review (at v2.5.1) especially targeting missing
error handling in callbacks. We also found some other issues but that's a
detail only.

More relevant findings are listed below. Less critical, or even findings with
refactoring character, we'll track in issue #60.

**Unusual Code**
[RedisQues.java:231](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L231):
    Switch-case fall through. Is this one expected? If yes: add comment. If
    not: QUICKLY ADD A BREAK THERE!

**Resource Leak**
[RedisQues.java:348](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L348):
    Who releases this acquired lock?

[RedisQues.java:379](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L379):
    event gets not resolved.

[RedisQues.java:950](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L950):
    handler gets never notified.

[RedisquesHttpRequestHandler.java:621](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L621):
    Handler gets not called.
    BTW: Why is this a _Handler< Void>_? I expected a _Handler<AsyncResult< Void>>_.

**Missing Error Handling**
[RedisquesHttpRequestHandler.java:211](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L211):
[RedisquesHttpRequestHandler.java:228](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L228):
[RedisquesHttpRequestHandler.java:249](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L249):
[RedisquesHttpRequestHandler.java:255](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L255):
[RedisquesHttpRequestHandler.java:269](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L269):
[RedisquesHttpRequestHandler.java:468](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L468):
[RedisquesHttpRequestHandler.java:491](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L491):
[RedisquesHttpRequestHandler.java:502](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L502):
[RedisquesHttpRequestHandler.java:522](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L522):
[RedisquesHttpRequestHandler.java:534](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L534):
[RedisquesHttpRequestHandler.java:540](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L540):
[RedisquesHttpRequestHandler.java:617](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L617):
    Missing error handling for _reply_.

[LuaScriptState.java:98](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/lua/LuaScriptState.java#L98):
    Access result of AsyncResult (variable newSha) used without error check.

[MessageUtil.java:20](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/MessageUtil.java#L20):
    Access result of body() without null check.
    (Hmm is a null check really a good idea here?)

[RedisQues.java:124](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L124):
    Not dramatical because not used but: event result is never checked.

[RedisQues.java:194](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L194):
    Use of return value from event.body() without error/null check.

[RedisQues.java:292](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L292):
    (Maybe) we should check error state before delegating.

[RedisQues.java:306](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L306):
    Missing error handling for event1.

[RedisQues.java:435](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L435):
    replyLrem.success() is never checked

[RedisQues.java:449](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L449):
    unlockReply.success() is never checked

[RedisQues.java:761](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L761):
    May we should at least log in case event failed.

[RedisQues.java:808](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L808):
    May we should at least log in case refreshRegistration failed.

[RedisQues.java:858](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L858):
    Is it correct, to assume a queue is not locked in case query failed?

[RedisQues.java:882](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L882):
    With null check we'll miss real failures. We should at least log if fail() == true.

[RedisQues.java:891](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L891):
    Why we ignore success/failure of jsonAnswer? IMO we at least should log
    in case of a failure.

[RedisQues.java:1004](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L1004):
    Here we blindly assume no consumer is the same as error on event bus.

[RedisQues.java:1084](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L1084):
    We miss to check if message failed.

**Comment by hiddenalpha** [comment]
Created [temporary PR](https://github.com/hiddenalpha/vertx-redisques/pull/1) for discussions.

**Comment by hiddenalpha** [comment]
We, (I, @oli-h, @ljucam) decided to only handle the case which that issue came from.
All other cases, we'll only log without introducing changes in code flow. This is to address users of this module which may depend on falsy behavior.

Therefore I'll make further changes now.

**Comment by mcweba** [comment]
Released in version [v2.5.4](https://github.com/swisspush/vertx-redisques/releases/tag/v2.5.4)
