### ISSUE TITLE
Less relevant findings from code (review of v2.5.1)

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/vertx-redisques#60]
Here the less relevant findings from code review (More important findings
are tracked in #59).

**Missing logging**
[LuaScriptManager.java:84](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/lua/LuaScriptManager.java#L84):
    Why log only the message without the stack?

[MessageUtil.java:29](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/MessageUtil.java#L29):
    Is it the way to go to use only msg of exception?

[RedisQues.java:438](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L438):
    event1.cause() is ignored. I think at least we should log it.

[RedisQues.java:493](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L493):
    delManyReply.cause() is ignored. I think at least we should log it.

[RedisQues.java:502](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L502):
    reply.cause() is ignored. I think at least we should log it.

[RedisQues.java:949](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L949):
    Why only log message? I suggest to log the whole exception.

[RedisquesHttpRequestHandler.java:64](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L64):
    Why not log the stack trace? (Pass cause as 2nd param) This also would save
    us from a possible NullPointerException.

**Refactoring**
[RedisquesHttpRequestHandler.java:229](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L229):
    _reply.result().body()_ gets called over and over again. Why not call that once
    and reuse that reference?

[RedisquesHttpRequestHandler.java:256](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L256):
    _ctx.response()_ gets called over and over again. Why not call once and
    reuse that reference?

[RedisquesHttpRequestHandler.java:274](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L274):
[RedisquesHttpRequestHandler.java:306](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L306):
[RedisquesHttpRequestHandler.java:324](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L324):
    Why call getter chain _reply.result().body()_ multiple times instead once
    and reuse reference?

[RedisquesHttpRequestHandler.java:499](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L499):
    Repeated call to same getter chain _ctx.request().path()_ 3 times.

[RedisquesHttpRequestHandler.java:356](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java#L356):
    Why not log _reply.cause()_?

[HttpServerRequestUtil.java:58](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L58):
[HttpServerRequestUtil.java:61](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L61):
[HttpServerRequestUtil.java:63](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L63):
[HttpServerRequestUtil.java:65](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L65):
    Why do we use string here as error type?

[RedisquesAPI.java:162](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/RedisquesAPI.java#L162):
[RedisquesAPI.java:174](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/RedisquesAPI.java#L174):
[RedisquesAPI.java:214](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/RedisquesAPI.java#L214):
    Using Optional<> as method argument?!? Even IntelliJ warns about that.

[RedisquesAPI.java:43](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/RedisquesAPI.java#L43):
    An enum with lower case constants?!?

[RedisquesConfiguration.java:251](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java#L251):
    I recommend to extract this class in its own file. I think there's enough
    code for that. If not, we should at least drop the useless name duplication
    in this inner class. IMO Builder should suffice.

[RedisQues.java:123](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L123):
    Why not use private method and reference it by method reference?

[RedisQues.java:291](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L291):
    (Maybe) add logger enabled check before concat strings.

[RedisQues.java:464](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L464):
    Why not use queues.size() to initialize the ArrayList?

[RedisQues.java:619](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L619):
    May we should catch java.lang.ClassCastException explicitly to make
    intent more obvious.

[RedisQues.java:876](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L876):
    We'll run into a NullPointerException in case lockAnswer failed. Sure:
    Current implementation will never reject that returned promise. But will
    this be true forever?

[RedisQues.java:894](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L894):
[RedisQues.java:919](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L919):
    (Relates to next finding)
    Why do we cancel that timer? This seems we've to cleanup resource we didn't
    acquire. IMO this should be handled inside processMessageWithTimeout. And
    Yey: It already IS handled in there. It seems to be a one-shot timer.
    Therefore why do we need to cancel that timer then?

[RedisQues.java:974](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L974):
    (Relates to previous finding)
    We shouldn't pass that timeoutId here. Instead we should cancel the timer
    before calling callback.

[RedisQues.java:1026](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L1026):
[RedisQues.java:1042](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L1042):
[RedisQues.java:1115](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L1115):
    Useless null check: Why not simply pass null here? Vertx properly makes
    null checks and we don't need to spawn object for nothing.

[RedisQues.java:980](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L980):
    What is this type for? Why not use vertx AsyncResult?

**Missing doc**
[HttpServerRequestUtil.java:75](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L75):
[HttpServerRequestUtil.java:76](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L76):
    We should document declared exception. Reason for this is JsonObject ctor
    on first line which may throws io.vertx.core.json.DecodeException.

[RedisQues.java:205](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/RedisQues.java#L205):
    Missing fail check of Message event in nearly all callees here. Caller
    should handle that. Therefore document this expectation in EVERY callee.

[HttpServerRequestUtil.java:76](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L76):
    (Relates to next finding)
    Declares to throw Exception BUT doesn't state WHY. Javadoc should mention
    the exception something like: "Throws Exception if decoding failed".

[HttpServerRequestUtil.java:76](https://github.com/swisspush/vertx-redisques/blob/v2.5.1/src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java#L76):
    (Relates to previous finding)
    There should be a comment (NOT javadoc) explaining, that new JsonObject()
    may throws io.vertx.core.json.DecodeException. This would show to the
    developer, why this method is declared to throw an Exception. If this is
    missing, someone may remove the throws declaration because he've no
    knowledge about the internals of this constructor.

**Comment by mcweba** [comment]
Released in version [v2.5.4](https://github.com/swisspush/vertx-redisques/releases/tag/v2.5.4)
