### ISSUE TITLE
Limited retries for queue items

### ISSUE THREAD

**Issue by mcweba** [swisspush/vertx-redisques#73]
Normally a queue item resides in the queue until it was either successfully processed or deleted. We have a use case where we want to automatically remove a queue item after a configurable amount of retries, so the next queue item can be processed.

The retry count should only be tracked in memory. There's no need to store the retry count to the redis database.

**Comment by lbovet** [comment]
Mmh. This smells a bit. Is the backend rejecting the message or the backend not accessible?
We decide to lose messages on a wacky base.
Could we discuss the need for such a hacky thing?

**Comment by mcweba** [comment]
We have the following situation where this could be useful: Forwarding requests via route hook (dynamically adds correct token information for authentication) to Google's Firebase Messaging API. Such requests to publish messages can either be targeted to a topic or a token. The token (from client) can expire, resulting in a 404 Not Found response from Google. Since we're sending these requests to a queue, such 404 responses block the queue.

Our current solution is now to define a _x-queue-expire-after_ header for these queue items. The problem here is, that a bad queue item blocks the queue and when finally removed, the second queue item might be valid but already expired.

A maybe better solution would be to allow the definition of a translate status (like in real routing rules) for hook routes.

**Comment by lbovet** [comment]
Oh yes, I think the translate status is the correct way to handle this.
